/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EjercicioTV;

import javax.swing.ImageIcon;
import javax.swing.ImageIcon;
import java.awt.Image; 

/**
 *
 * @author delcenjo
 */
public class JFramePrincipal extends javax.swing.JFrame {
    
    private boolean estado = false;
    private int canal = 0;
    private int volume = 0;
    
    String TvOff = "21.png";
    String TvOn = "226777.png";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFramePrincipal.class.getName());

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/EjercicioTV/21.png")));
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/EjercicioTV/226777.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        btnEncender = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LabelChanel = new javax.swing.JLabel();
        varChanLow = new javax.swing.JButton();
        varChanUp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelVolumen = new javax.swing.JLabel();
        btnValumeLess = new javax.swing.JButton();
        btnVolumePlus = new javax.swing.JButton();
        imagenTV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estado:");

        labelEstado.setText("Apagado");

        btnEncender.setText("Encender");
        btnEncender.addActionListener(this::btnEncenderActionPerformed);

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(this::btnApagarActionPerformed);

        jLabel2.setText("Canal:");

        LabelChanel.setText("0");

        varChanLow.setText("Canal -");
        varChanLow.addActionListener(this::varChanLowActionPerformed);

        varChanUp.setText("Canal +");
        varChanUp.addActionListener(this::varChanUpActionPerformed);

        jLabel3.setText("Valomen");

        labelVolumen.setText("0");

        btnValumeLess.setText("Volume -");
        btnValumeLess.addActionListener(this::btnValumeLessActionPerformed);

        btnVolumePlus.setText("Volume +");
        btnVolumePlus.addActionListener(this::btnVolumePlusActionPerformed);

        imagenTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EjercicioTV/21.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelEstado))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelChanel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenTV, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(varChanLow)
                                    .addComponent(btnEncender)
                                    .addComponent(btnValumeLess))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnApagar)
                                            .addComponent(varChanUp)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(btnVolumePlus)))))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApagar)
                    .addComponent(btnEncender))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabelChanel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varChanLow)
                    .addComponent(varChanUp))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelVolumen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValumeLess)
                    .addComponent(btnVolumePlus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(imagenTV, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        if(estado == false){
            estado = true;
            labelEstado.setText("Encendido");
            imagenTV.setIcon(new ImageIcon(getClass().getResource(TvOn)));
        }else{
            System.out.println("El televisor ya esta encendido");
        }
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        if(estado == true){
            estado = false;
            labelEstado.setText("Apagado");
            imagenTV.setIcon(new ImageIcon(getClass().getResource(TvOff)));            
        }else{
            System.out.println("El televisor ya esta apagado");
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void varChanLowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varChanLowActionPerformed
        if(estado){
        canal--;
        LabelChanel.setText(String.valueOf(canal));            
        }else{
            System.out.println("Para cambiar de canal, primero enciende la TV");
        }
    }//GEN-LAST:event_varChanLowActionPerformed

    private void varChanUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varChanUpActionPerformed
        if(estado){
        canal++;
        LabelChanel.setText(String.valueOf(canal));            
        }else{
            System.out.println("Para cambiar de canal, primero enciende la TV");
        }
    }//GEN-LAST:event_varChanUpActionPerformed

    private void btnValumeLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValumeLessActionPerformed
        if(estado){
        volume--;
        labelVolumen.setText(String.valueOf(volume));            
        }else{
            System.out.println("Para bajar el volumen, primero enciende la TV");
        }        
    }//GEN-LAST:event_btnValumeLessActionPerformed

    private void btnVolumePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolumePlusActionPerformed
        if(estado){
        volume++;
        labelVolumen.setText(String.valueOf(volume));            
        }else{
            System.out.println("Para subir el volumen, primero enciende la TV");
        }      
    }//GEN-LAST:event_btnVolumePlusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelChanel;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEncender;
    private javax.swing.JButton btnValumeLess;
    private javax.swing.JButton btnVolumePlus;
    private javax.swing.JLabel imagenTV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelVolumen;
    private javax.swing.JButton varChanLow;
    private javax.swing.JButton varChanUp;
    // End of variables declaration//GEN-END:variables
}
